#ifndef CONFIG_H
#define CONFIG_H

#define PHILOSOPHER_DINNER_TIME_RANGE_MIN_MS 50
#define PHILOSOPHER_DINNER_TIME_RANGE_MAX_MS 500

#define PHILOSOPHER_THINKING_TIME_RANGE_MIN_MS 50
#define PHILOSOPHER_THINKING_TIME_RANGE_MAX_MS 500

#define DINING_TABLE_PHILOSOPHERS_NUMBER 10

#define RANDOM_POOL_SIZE 1024

#endif
